<?php
function wv_custom_follow_networks_alter(&$networks, $uid = 0) {
    drupal_add_css(drupal_get_path('module', 'wv_custom') . '/styles.css', array('group' => CSS_DEFAULT, 'every_page' => FALSE));
    $networks[$uid]['imdb'] = array(
        'title' => t('IMDB'),
        'domain' => 'imdb.com',
    );
    $networks[$uid]['drupal'] = array(
        'title' => t('Drupal.org'),
        'domain' => 'drupal.org',
    );
    $networks[$uid]['etsy'] = array(
        'title' => t('Etsy'),
        'domain' => 'etsy.com',
    );
    $networks[$uid]['redbubble'] = array(
        'title' => 'Red Bubble',
        'domain' => 'redbubble.com',
    );
}
